version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'Tech__himalaya'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
